image: $PLUGIN_BUILDER_IMAGE

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.

stages:
  - build
  - reporting

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_SUBMODULE_STRATEGY: recursive
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - get_iiq_binaries ./lib/iiq/  identityiq connector-bundle-identityiq connector-bundle
    - ./gradlew
  artifacts:
    paths:
      - build/distributions/*.zip
    # expire_in: 1 month

reporting:
  stage: reporting
  image: $BADGE_GENERATOR_IMAGE
  needs: ["build"]
  script:
    - python $BADGE_GENERATOR
  artifacts:
    paths:
      - ./badges/*.svg
